
name: Refresh Grade Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]

jobs:
  refresh-grades:
    name: Refresh Grades
    runs-on: ubuntu-latest
    container:
      image: cansav09/metricminer

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Refresh DataTrail Grades Sheet
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GOOGLECLASSROOM_ACCESS: ${{ secrets.GOOGLECLASSROOM_ACCESS }}
          GOOGLECLASSROOM_REFRESH: ${{ secrets.GOOGLECLASSROOM_REFRESH }}
          METRICMINER_GOOGLE_ACCESS: ${{ secrets.METRICMINER_GOOGLE_ACCESS }}
          METRICMINER_GOOGLE_REFRESH: ${{ secrets.METRICMINER_GOOGLE_REFRESH }}
        run: |
         Rscript pull-quiz-grades.R
